all: download_alignments


#Robinson J, Barker DJ, Georgiou X, Cooper MA, Flicek P, Marsh SGE: IPD-IMGT/HLA Database. Nucleic Acids Research (2020), 48:D948-55
#Robinson J, Malik A, Parham P, Bodmer JG, Marsh SGE: IMGT/HLA - a sequence database for the human major histocompatibility complex Tissue Antigens (2000), 55:280-287
download_alignments:
	wget ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/msf/A_prot.msf
	wget ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/msf/B_prot.msf
	wget ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/msf/C_prot.msf
	wget ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/msf/DRB1_prot.msf
	wget ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/msf/DQA1_prot.msf
	wget ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/msf/DQB1_prot.msf